/**
 * Build-time Shiki for the landing page only. Keeps the client bundle free of Shiki on `/`.
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createHighlighter } from "shiki";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const previewCodeClass =
  "mt-4 max-w-full overflow-x-auto rounded-xl border border-areia-border text-xs [&_pre]:min-w-max [&_pre]:p-4 [&_pre]:text-xs [&_pre]:leading-relaxed";

const fileTreeCode = `src
├─ lib/components
│  ├─ footer.tsx
│  └─ topbar.tsx
├─ pages
│  ├─ index.tsx
│  ├─ +layout.tsx
│  └─ (content)
│     ├─ getting-started.mdx
│     └─ guide/writing.mdx
├─ app.css
└─ main.ts

luzpress provides search, theme, MDX helpers`;

const mdxSyntaxCode = `import { Button } from "areia"

# Writing great docs

Use Markdown for prose, lists, and examples.

\`\`\`ts
const path = "/guide/writing"
\`\`\`

<Button>Try it</Button>`;

const buildOutputCode = `$ bun run build
✓ dist/index.html
✓ dist/getting-started/index.html
✓ dist/guide/writing/index.html

Deploy the dist/ folder anywhere.`;

function wrap(html: string) {
  return `<div class="${previewCodeClass}">${html}</div>`;
}

const highlighter = await createHighlighter({
  themes: ["night-owl-light", "houston"],
  langs: ["shell", "mdx"],
});

const previews = {
  fileTree: wrap(
    highlighter.codeToHtml(fileTreeCode, {
      lang: "shell",
      themes: { light: "night-owl-light", dark: "houston" },
    }),
  ),
  mdxSyntax: wrap(
    highlighter.codeToHtml(mdxSyntaxCode, {
      lang: "mdx",
      themes: { light: "night-owl-light", dark: "houston" },
    }),
  ),
  buildOutput: wrap(
    highlighter.codeToHtml(buildOutputCode, {
      lang: "shell",
      themes: { light: "night-owl-light", dark: "houston" },
    }),
  ),
};

const out = join(root, "src/lib/hero-preview-html.generated.ts");
const body = `// Generated by scripts/gen-hero-previews.ts — do not edit.
export const heroPreviewHtml = ${JSON.stringify(previews)} as const;
`;

writeFileSync(out, body);
console.log("wrote", out);
