import fs from "node:fs";
import path from "node:path";

export type LuzpressLlmsOptions = {
  /** H1 title in llms.txt. Defaults to package.json name or "Documentation". */
  siteName?: string;
  /** Blockquote summary in llms.txt. */
  summary?: string;
  /** H2 section heading for doc links. Defaults to "Docs". */
  section?: string;
};

type ContentFile = {
  sourcePath: string;
  routePath: string;
  distRelative: string;
  title: string;
  content: string;
  ext: string;
};

function normalizeContentDirPhysical(root: string, contentDir: string) {
  const trimmed = contentDir.replace(/^\/+|\/+$/g, "").replace(/^src\//, "");
  return path.join(root, "src", trimmed);
}

function filePathToRoutePath(filePath: string, contentDirPhysical: string) {
  const relative = path
    .relative(contentDirPhysical, filePath)
    .replace(/\\/g, "/")
    .replace(/\.mdx?$/, "")
    .replace(/\/index$/, "");

  if (!relative || relative === "index") return "/";
  return `/${relative}`;
}

function titleize(value: string) {
  return value.replace(/[-_]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function titleFromSource(content: string, filePath: string) {
  const heading = content.match(/^#\s+(.+)$/m);
  if (heading) return heading[1].trim();

  const name = path.basename(filePath).replace(/\.mdx?$/, "");
  return titleize(name === "index" ? "overview" : name);
}

function routeToDistRelative(routePath: string) {
  if (routePath === "/") return "index.md";
  return `${routePath.slice(1)}/index.md`;
}

function collectContentFiles(contentDirPhysical: string): ContentFile[] {
  if (!fs.existsSync(contentDirPhysical)) return [];

  const files: ContentFile[] = [];

  function walk(dir: string) {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const entryPath = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        walk(entryPath);
        continue;
      }

      if (!/\.mdx?$/.test(entry.name)) continue;

      const content = fs.readFileSync(entryPath, "utf8");
      const routePath = filePathToRoutePath(entryPath, contentDirPhysical);

      files.push({
        sourcePath: entryPath,
        routePath,
        distRelative: routeToDistRelative(routePath),
        title: titleFromSource(content, entryPath),
        content,
        ext: ".md",
      });
    }
  }

  walk(contentDirPhysical);

  return files.sort((a, b) => a.routePath.localeCompare(b.routePath));
}

function renderLlmsOutline(files: ContentFile[], options: Required<LuzpressLlmsOptions>) {
  const lines = [
    `# ${options.siteName}`,
    "",
    `> ${options.summary}`,
    "",
    `## ${options.section}`,
    "",
  ];

  for (const file of files) {
    lines.push(`- [${file.title}](/${file.distRelative})`);
  }

  lines.push(
    "",
    "## Full text",
    "",
    "- [llms-full.txt](/llms-full.txt): Complete documentation dump",
  );

  return `${lines.join("\n")}\n`;
}

function renderLlmsFull(files: ContentFile[]) {
  return files
    .map((file) => {
      return [
        `# ${file.title}`,
        "",
        `Route: ${file.routePath}`,
        `Source: /${file.distRelative}`,
        "",
        file.content,
      ].join("\n");
    })
    .join("\n\n---\n\n")
    .concat("\n");
}

function readSiteName(root: string) {
  try {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")) as {
      name?: string;
    };
    if (pkg.name) return titleize(pkg.name.replace(/^@[^/]+\//, "").replace(/-/g, " "));
  } catch {
    // ignore
  }

  return "Documentation";
}

export function generateLlmsArtifacts(options: {
  root?: string;
  outDir: string;
  contentDir: string;
  llms?: boolean | LuzpressLlmsOptions;
}) {
  if (options.llms === false) return;

  const root = options.root ?? process.cwd();
  const contentDirPhysical = normalizeContentDirPhysical(root, options.contentDir);
  const files = collectContentFiles(contentDirPhysical);
  if (files.length === 0) return;

  const llmsOptions = typeof options.llms === "object" ? options.llms : {};
  const resolved: Required<LuzpressLlmsOptions> = {
    siteName: llmsOptions.siteName ?? readSiteName(root),
    summary: llmsOptions.summary ?? "Documentation site generated by luzpress.",
    section: llmsOptions.section ?? "Docs",
  };

  fs.mkdirSync(options.outDir, { recursive: true });

  for (const file of files) {
    const distPath = path.join(options.outDir, file.distRelative);
    fs.mkdirSync(path.dirname(distPath), { recursive: true });
    fs.copyFileSync(file.sourcePath, distPath);
  }

  fs.writeFileSync(path.join(options.outDir, "llms.txt"), renderLlmsOutline(files, resolved));
  fs.writeFileSync(path.join(options.outDir, "llms-full.txt"), renderLlmsFull(files));
}
