import { defineConfig } from "vite";
import { luzpress } from "luzpress";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    luzpress({
      hostname: "https://luz.ilha.build",
      repo: "https://github.com/ilhajs/luz",
      repoPath: "templates/starter",
      shiki: {
        themes: { light: "night-owl-light", dark: "houston" },
        langs: ["ts", "mdx", "shell"],
      },
      head: {
        title: "Luz — Documentation starter for Ilha",
      },
      navItems: [{ label: "Documentation", url: "/getting-started" }],
      socials: [
        { service: "x", url: "https://x.com/ilha_js" },
        { service: "discord", url: "https://discord.gg/WnVTMCTz74" },
        { service: "github", url: "https://github.com/ilhajs/luz" },
      ],
      preview: {
        importmap: JSON.stringify({
          imports: {
            ilha: "https://esm.sh/ilha@0.7.0",
            "ilha/jsx-runtime": "https://esm.sh/ilha@0.7.0/jsx-runtime",
            areia: "https://esm.sh/areia?deps=ilha@0.7.0",
          },
        }),
        head: [
          `<script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>`,
          `<style type="text/tailwindcss">`,
          `  @theme {`,
          `    --color-areia-background: var(--color-white, #fff);`,
          `    --color-areia-foreground: oklch(21% 0.006 285.885);`,
          `    --color-areia-surface: var(--color-white, #fff);`,
          `    --color-areia-surface-muted: oklch(97% 0 0);`,
          `    --color-areia-surface-elevated: var(--color-white, #fff);`,
          `    --color-areia-overlay: oklch(0% 0 0 / 0.4);`,
          `    --color-areia-border: oklch(93.5% 0 0);`,
          `    --color-areia-ring: #ff7a37;`,
          `    --color-areia-divider: oklch(14.5% 0 0 / 0.1);`,
          `    --color-areia-primary: #ff7a37;`,
          `    --color-areia-primary-foreground: var(--color-white, #fff);`,
          `    --color-areia-destructive: oklch(63.7% 0.237 25.331);`,
          `    --color-areia-destructive-foreground: var(--color-white, #fff);`,
          `    --color-areia-text-default: oklch(21% 0.006 285.885);`,
          `    --color-areia-text-strong: oklch(14.5% 0 0);`,
          `    --color-areia-text-subtle: oklch(55.6% 0 0);`,
          `    --color-areia-text-muted: oklch(70.8% 0 0);`,
          `    --color-areia-text-disabled: oklch(87% 0 0);`,
          `    --color-areia-control-background: var(--color-white, #fff);`,
          `    --color-areia-control-foreground: oklch(21% 0.006 285.885);`,
          `    --color-areia-control-border: oklch(93.5% 0 0);`,
          `    --color-areia-control-hover: oklch(97% 0 0);`,
          `    --color-areia-control-disabled: oklch(100% 0 0 / 0.5);`,
          `    --color-areia-control-disabled-foreground: oklch(87% 0 0);`,
          `  }`,
          `  .dark {`,
          `    --color-areia-background: oklch(10% 0 0);`,
          `    --color-areia-foreground: oklch(97% 0 0);`,
          `    --color-areia-surface: oklch(17% 0 0);`,
          `    --color-areia-surface-muted: oklch(26.9% 0 0);`,
          `    --color-areia-surface-elevated: oklch(20% 0 0);`,
          `    --color-areia-border: oklch(26.9% 0 0);`,
          `    --color-areia-divider: oklch(26.9% 0 0);`,
          `    --color-areia-text-default: oklch(97% 0 0);`,
          `    --color-areia-text-strong: oklch(98.5% 0 0);`,
          `    --color-areia-text-subtle: oklch(70.8% 0 0);`,
          `    --color-areia-text-muted: oklch(55.6% 0 0);`,
          `    --color-areia-text-disabled: oklch(43.9% 0 0);`,
          `    --color-areia-control-background: oklch(17% 0 0);`,
          `    --color-areia-control-foreground: oklch(97% 0 0);`,
          `    --color-areia-control-border: oklch(26.9% 0 0);`,
          `    --color-areia-control-hover: oklch(26.9% 0 0);`,
          `    --color-areia-control-disabled: oklch(17% 0 0 / 0.5);`,
          `    --color-areia-control-disabled-foreground: oklch(43.9% 0 0);`,
          `  }`,
          `  body { background: var(--color-areia-background, white); color: var(--color-areia-text-default); padding: 1rem; }`,
          `</style>`,
        ].join("\n"),
      },
    }),
  ],
});
